export const users = [
  {
    id: 1,
    nombre: 'Aitor',
    apellidos: 'Martínez',
    origen: 'Almacén 1, Madrid',
    destino: 'Almacén 2, Zaragoza',
    fecha: '19/10/2024',
    estado: 'En revisión',
    contacto: '666 444 333',
  },
  {
    id: 2,
    nombre: 'Lucía',
    apellidos: 'García',
    origen: 'Almacén 3, Valencia',
    destino: 'Almacén 5, Bilbao',
    fecha: '20/10/2024',
    estado: 'En envío',
    contacto: '677 555 444',
  },
  {
    id: 3,
    nombre: 'Carlos',
    apellidos: 'Pérez',
    origen: 'Almacén 4, Sevilla',
    destino: 'Almacén 6, Barcelona',
    fecha: '21/10/2024',
    estado: 'En revisión',
    contacto: '688 666 555',
  },
  {
    id: 4,
    nombre: 'Marta',
    apellidos: 'López',
    origen: 'Almacén 2, Zaragoza',
    destino: 'Almacén 7, Málaga',
    fecha: '22/10/2024',
    estado: 'En envío',
    contacto: '699 777 666',
  },
  {
    id: 5,
    nombre: 'Javier',
    apellidos: 'Rodríguez',
    origen: 'Almacén 5, Bilbao',
    destino: 'Almacén 1, Madrid',
    fecha: '23/09/2024',
    estado: 'En revisión',
    contacto: '611 888 777',
  },
  {
    id: 6,
    nombre: 'Ana',
    apellidos: 'Martín',
    origen: 'Almacén 6, Barcelona',
    destino: 'Almacén 3, Valencia',
    fecha: '24/09/2024',
    estado: 'En revisión',
    contacto: '622 999 888',
  },
  {
    id: 7,
    nombre: 'Pablo',
    apellidos: 'Sánchez',
    origen: 'Almacén 7, Málaga',
    destino: 'Almacén 4, Sevilla',
    fecha: '25/09/2024',
    estado: 'En envío',
    contacto: '633 000 999',
  },
  {
    id: 8,
    nombre: 'Laura',
    apellidos: 'Fernández',
    origen: 'Almacén 1, Madrid',
    destino: 'Almacén 8, Bilbao',
    fecha: '26/09/2024',
    estado: 'En revisión',
    contacto: '644 111 222',
  },
  {
    id: 9,
    nombre: 'Pedro',
    apellidos: 'Ruiz',
    origen: 'Almacén 3, Valencia',
    destino: 'Almacén 2, Zaragoza',
    fecha: '27/08/2024',
    estado: 'En envío',
    contacto: '655 222 333',
  },
  {
    id: 10,
    nombre: 'Elena',
    apellidos: 'Gómez',
    origen: 'Almacén 4, Sevilla',
    destino: 'Almacén 5, Bilbao',
    fecha: '28/08/2024',
    estado: 'En revisión',
    contacto: '666 333 444',
  },
];
